# Generated by Django 3.2.14 on 2022-07-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj3_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='place',
        ),
    ]
