# Generated by Django 3.2.14 on 2022-07-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj3_app', '0002_auto_20220712_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='plase',
            new_name='place',
        ),
    ]
